version: '2'
services:
  bundle:
    image: aact2_server
    volumes:
      - .:/var/www/app
    env_file:
      - server.env
    links:
      - 'db:postgres.db.host'
    entrypoint: ['bundle']
  rails:
    image: aact2_server
    volumes:
      - .:/var/www/app
    env_file:
      - server.env
    links:
      - 'db:postgres.db.host'
    entrypoint: ['rails']
  rake:
    image: aact2_server
    volumes:
      - .:/var/www/app
    env_file:
      - server.env
    links:
      - 'db:postgres.db.host'
    entrypoint: ['rake']
  rspec:
    image: aact2_server
    volumes:
      - .:/var/www/app
    env_file:
      - server.env
    environment:
      - RAILS_ENV=docker_test
    links:
      - 'db:postgres.db.host'
    entrypoint: ['rspec']
    command: spec
